import { createRepositoryAuthoredLevelContent } from "@motion-levels-games/published-level-runtime/source";
import type { AuthoredGameSourceManifest } from "@motion-levels-games/published-level-runtime";
import gameSource from "../content/game.json" with { type: "json" };
import level0 from "../content/levels/2cd08eb9-cc92-46fd-80ae-c87066495b4c.json" with { type: "json" };
import level1 from "../content/levels/5cdba430-c1a2-43de-8674-9210feb1d682.json" with { type: "json" };
import level2 from "../content/levels/690300be-0983-4c81-80f3-54d4bbdef274.json" with { type: "json" };
import level3 from "../content/levels/6e15748b-d27e-415d-8d5e-81a20e98d47e.json" with { type: "json" };
import level4 from "../content/levels/6e3eea3f-5183-4ec6-82f1-813a517ff942.json" with { type: "json" };
import level5 from "../content/levels/70a10100-7d0c-4c56-8e31-dfe354fe3423.json" with { type: "json" };
import level6 from "../content/levels/78e406fd-b26b-4ed5-8d4c-fe99522fe74a.json" with { type: "json" };
import level7 from "../content/levels/7e1a3af1-6b9a-4992-89ca-3752ba0d475c.json" with { type: "json" };
import level8 from "../content/levels/81ff2a76-79e5-4fe4-8dc9-e400081e10cc.json" with { type: "json" };
import level9 from "../content/levels/82f2d296-e5d0-456e-8de2-0571fb1c6850.json" with { type: "json" };
import level10 from "../content/levels/aef487d8-0686-43c3-8e28-733237daaa5a.json" with { type: "json" };
import level11 from "../content/levels/b7abc854-12db-413c-8eb8-09b56881cc6c.json" with { type: "json" };
import level12 from "../content/levels/e0db6120-ab2c-40d8-82e8-d9a599077005.json" with { type: "json" };
import level13 from "../content/levels/e6457bc3-c1d0-426f-8e4d-97483210c8d1.json" with { type: "json" };
import level14 from "../content/levels/f036fbc4-6cc1-40f0-8894-169b160fbf8f.json" with { type: "json" };
import resultAnimation0 from "../content/result-animations/d8db3406-f815-4a69-840d-1cea1a43facc.json" with { type: "json" };
import resultAnimation1 from "../content/result-animations/f72daac4-27a5-4144-b143-a6a85a34c3ec.json" with { type: "json" };

// Generated by npm run content:build. Edit content/*.json, not this file.
export const fallbackContent = createRepositoryAuthoredLevelContent({
  game: gameSource as AuthoredGameSourceManifest,
  levels: [level0, level1, level2, level3, level4, level5, level6, level7, level8, level9, level10, level11, level12, level13, level14],
  resultAnimations: [resultAnimation0, resultAnimation1],
  contentRevision: "2c515762a1c25831d1b9a1ba07e61cc4d7ab70644f1762fbd32cc184beeb7c63"
});

export const authoredContentSource = Object.freeze({
  game: "parkour",
  gameId: "c1daea4f-e586-4116-8cbe-871cde887a81",
  contentRevision: fallbackContent.contentRevision
});
