import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { bundleContentDigest, bundleFiles } from "./bundle-files.ts";

const root = path.resolve(process.env.MOTION_LEVELS_GAMES_BUNDLE_DIR || path.join(process.cwd(), "dist/bundle"));
const manifest = JSON.parse(await readFile(path.join(root, "bundle.json"), "utf8")) as {
  schema?: string;
  contractVersion?: number;
  venueRuntime?: { entry?: string; apiProtocolVersion?: number; controllerProtocolVersion?: number; games?: string[] };
  playerMenu?: { entry?: string; adapterProtocolVersion?: number };
  playerDisplay?: { entry?: string; games?: string[] };
  playground?: { entry?: string; basePath?: string };
  sourceRevision?: string;
  sdkFps?: number;
  artifactDigest?: string;
  files?: unknown[];
};
assert.equal(manifest.schema, "motion-levels-games-bundle-v2");
assert.equal(manifest.contractVersion, 2);
assert.equal(manifest.venueRuntime?.entry, "venue/runtime.mjs");
assert.equal(manifest.venueRuntime?.apiProtocolVersion, 1);
assert.equal(manifest.venueRuntime?.controllerProtocolVersion, 2);
assert.ok((manifest.venueRuntime?.games?.length ?? 0) > 0);
assert.equal(manifest.playerDisplay?.entry, "display/display.js");
assert.deepEqual(manifest.playerDisplay?.games, manifest.venueRuntime?.games);
assert.equal(manifest.playerMenu?.entry, "menu/index.html");
assert.equal(manifest.playerMenu?.adapterProtocolVersion, 1);
assert.equal(manifest.playground?.entry, "playground/index.html");
assert.equal(manifest.playground?.basePath, "/games/play/");
assert.equal(manifest.sdkFps, 50);
assert.match(String(manifest.sourceRevision), /^[0-9a-f]{40}$/u);
assert.equal("runtime" in manifest, false);
const files = await bundleFiles(root);
assert.ok(files.some((file) => file.path === manifest.venueRuntime?.entry), "venue runtime entry is missing from bundle files");
assert.ok(files.some((file) => file.path === manifest.playerDisplay?.entry), "player display entry is missing from bundle files");
assert.ok(files.some((file) => file.path === manifest.playerMenu?.entry), "player menu entry is missing from bundle files");
assert.ok(files.some((file) => file.path === manifest.playground?.entry), "playground entry is missing from bundle files");
assert.deepEqual(files, manifest.files);
assert.equal(bundleContentDigest(files), manifest.artifactDigest);
console.log(`Verified ${files.length} bundle files at ${manifest.artifactDigest}`);
