import { readFileSync } from "node:fs";
import {
  type RecordingAsset,
  type RecordingBoundary,
  type RecordingClient,
  type RecordingObservation,
  RecordingStartRejectedError,
  type SessionHistoryJsonObject
} from "@motion-levels-games/session-history";

export type HttpRecordingClientOptions = {
  baseUrl: string | URL;
  token?: string;
  timeoutMillis?: number;
  segmentSeconds?: number;
  maximumSessionSeconds?: number;
  stopPollIntervalMillis?: number;
  fetch?: typeof fetch;
};

/** Adapter for the camera service's transitional session boundary. Capture
 * identity is generated by history and sent to the camera as metadata because
 * the compatibility response does not currently echo a capture id. */
export class HttpRecordingClient implements RecordingClient {
  private readonly baseUrl: URL;
  private readonly request: typeof fetch;
  private readonly timeoutMillis: number;
  private readonly segmentSeconds: number;
  private readonly maximumSessionSeconds: number;
  private readonly stopPollIntervalMillis: number;

  constructor(private readonly options: HttpRecordingClientOptions) {
    this.baseUrl = new URL(options.baseUrl);
    if (this.baseUrl.protocol !== "http:" && this.baseUrl.protocol !== "https:") {
      throw new Error("camera recorder URL must use HTTP(S)");
    }
    this.request = options.fetch ?? fetch;
    this.timeoutMillis = Math.max(100, options.timeoutMillis ?? 20_000);
    this.segmentSeconds = boundedInteger(options.segmentSeconds, 10, 1_200, 300);
    this.maximumSessionSeconds = boundedInteger(options.maximumSessionSeconds, 60, 7_200, 7_200);
    this.stopPollIntervalMillis = Math.max(10, options.stopPollIntervalMillis ?? 100);
  }

  async onBoundary(boundary: RecordingBoundary): Promise<RecordingAsset> {
    const starting = boundary.type === "start";
    const captureId = boundary.recording.captureId ?? boundary.recording.id;
    const headers: Record<string, string> = {
      Accept: "application/json",
      "Content-Type": "application/json"
    };
    const token = this.options.token?.trim();
    if (token) headers.Authorization = `Bearer ${token}`;
    const occurredAtUnixNanos = (BigInt(boundary.occurredAtUnixMillis) * 1_000_000n).toString();
    const response = await this.request(
      new URL(starting ? "/sessions/start" : "/sessions/stop", this.baseUrl),
      {
        method: "POST",
        headers,
        body: JSON.stringify({
          venueSessionId: captureId,
          captureId,
          historySessionId: boundary.sessionId,
          historySelectionId: boundary.selectionId,
          historyRunId: boundary.runId,
          recordingScope: boundary.scope,
          cameraIds: boundary.policy.cameraIds,
          includeAudio: boundary.policy.includeAudio,
          startedUnixNanos: starting ? occurredAtUnixNanos : undefined,
          endedUnixNanos: starting ? undefined : occurredAtUnixNanos,
          reason: starting ? undefined : "history_boundary",
          segmentSeconds: this.segmentSeconds,
          maxSessionSeconds: this.maximumSessionSeconds
        }),
        signal: AbortSignal.timeout(this.timeoutMillis)
      }
    );
    const text = await response.text();
    let body: Record<string, unknown> = {};
    if (text) {
      try {
        const decoded: unknown = JSON.parse(text);
        if (decoded && typeof decoded === "object" && !Array.isArray(decoded)) {
          body = decoded as Record<string, unknown>;
        }
      } catch {
        // The HTTP status below remains authoritative.
      }
    }
    if (!response.ok) {
      throw new Error(`camera recorder returned HTTP ${response.status}${text ? `: ${text.slice(0, 200)}` : ""}`);
    }
    if (!starting && body.stopping === true) {
      await this.waitUntilStopped(captureId, headers);
    }

    const cameraStarted = starting && body.recording === true;
    if (starting && !cameraStarted) {
      throw new RecordingStartRejectedError(
        `camera recorder did not start capture ${captureId}: ${String(body.error ?? "camera unavailable")}`
      );
    }
    const maxEndsAtUnixMillis = unixMillis(body.maxEndsAt)
      ?? metadataInteger(boundary.recording, "cameraMaxEndsAtUnixMillis");
    return {
      ...boundary.recording,
      status: starting ? "recording" : "complete",
      captureId,
      backend: cleanString(body.backend) ?? boundary.recording.backend ?? "camera-recorder",
      startedAtUnixMillis: boundary.recording.startedAtUnixMillis
        ?? (starting ? boundary.occurredAtUnixMillis : undefined),
      endedAtUnixMillis: starting
        ? boundary.recording.endedAtUnixMillis
        : boundary.occurredAtUnixMillis,
      localPath: cleanString(body.videoFolderPath) ?? boundary.recording.localPath,
      shareUrl: cleanString(body.videoFolderShareUrl) ?? boundary.recording.shareUrl,
      metadata: {
        ...(boundary.recording.metadata ?? {}),
        cameraResponse: jsonObject(body),
        ...(maxEndsAtUnixMillis === undefined ? {} : { cameraMaxEndsAtUnixMillis: maxEndsAtUnixMillis }),
        ...(!starting && body.stopping === true ? { stopConfirmed: true } : {})
      }
    };
  }

  async observe(recording: RecordingAsset): Promise<RecordingObservation> {
    const captureId = recording.captureId ?? recording.id;
    const sessions = await this.activeSessions(this.headers());
    const session = sessions.find((candidate) => sessionMatches(candidate, captureId));
    return {
      active: Boolean(session),
      observedAtUnixMillis: Date.now(),
      maxEndsAtUnixMillis: unixMillis(session?.maxEndsAt)
        ?? metadataInteger(recording, "cameraMaxEndsAtUnixMillis")
    };
  }

  private async waitUntilStopped(captureId: string, headers: Record<string, string>): Promise<void> {
    const deadline = Date.now() + this.timeoutMillis;
    while (true) {
      const remaining = deadline - Date.now();
      if (remaining <= 0) throw new Error(`camera recorder did not stop capture ${captureId} before timeout`);
      const activeSessions = await this.activeSessions(headers, Math.max(100, Math.min(remaining, 2_000)));
      const active = activeSessions.some((session) => sessionMatches(session, captureId));
      if (!active) return;
      await new Promise<void>((resolve) => setTimeout(resolve, Math.min(this.stopPollIntervalMillis, remaining)));
    }
  }

  private headers(): Record<string, string> {
    const token = this.options.token?.trim();
    return {
      Accept: "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {})
    };
  }

  private async activeSessions(
    headers: Record<string, string>,
    timeoutMillis = Math.min(this.timeoutMillis, 2_000)
  ): Promise<SessionHistoryJsonObject[]> {
    const response = await this.request(new URL("/status", this.baseUrl), {
      method: "GET",
      headers: { Accept: "application/json", ...(headers.Authorization ? { Authorization: headers.Authorization } : {}) },
      signal: AbortSignal.timeout(timeoutMillis)
    });
    if (!response.ok) throw new Error(`camera recorder status returned HTTP ${response.status}`);
    const decoded: unknown = await response.json();
    if (!decoded || typeof decoded !== "object" || Array.isArray(decoded)) {
      throw new Error("camera recorder status response is invalid");
    }
    const activeSessions = (decoded as { activeSessions?: unknown }).activeSessions;
    if (!Array.isArray(activeSessions)
      || activeSessions.some((session) => !session || typeof session !== "object" || Array.isArray(session))) {
      throw new Error("camera recorder status response requires activeSessions");
    }
    return activeSessions.map((session) => jsonObject(session));
  }
}

export function recordingClientFromEnvironment(
  environment: NodeJS.ProcessEnv = process.env,
  request?: typeof fetch
): RecordingClient | null {
  const baseUrl = environment.MOTION_LEVELS_CAMERA_RECORDER_URL?.trim();
  if (!baseUrl) return null;
  let token = environment.MOTION_LEVELS_CAMERA_RECORDER_TOKEN?.trim() ?? "";
  const tokenFile = environment.MOTION_LEVELS_CAMERA_RECORDER_TOKEN_FILE?.trim();
  if (!token && tokenFile) {
    try {
      token = readFileSync(tokenFile, "utf8").trim();
    } catch {
      // A configured recorder with a missing token should fail visibly at the
      // boundary and degrade history health instead of disabling recording.
    }
  }
  return new HttpRecordingClient({
    baseUrl,
    token,
    timeoutMillis: durationMillis(environment.MOTION_LEVELS_CAMERA_RECORDER_TIMEOUT, 20_000),
    segmentSeconds: Number(environment.MOTION_LEVELS_CAMERA_RECORDER_SEGMENT_SECONDS),
    maximumSessionSeconds: Number(environment.MOTION_LEVELS_CAMERA_SESSION_MAX_SECONDS),
    stopPollIntervalMillis: durationMillis(environment.MOTION_LEVELS_CAMERA_RECORDER_POLL_INTERVAL, 100),
    fetch: request
  });
}

function durationMillis(value: string | undefined, fallback: number): number {
  const match = /^(\d+(?:\.\d+)?)(ms|s)?$/u.exec(String(value ?? "").trim().toLowerCase());
  if (!match) return fallback;
  const amount = Number(match[1]);
  if (!Number.isFinite(amount) || amount <= 0) return fallback;
  return Math.max(100, Math.round(amount * (match[2] === "s" ? 1_000 : 1)));
}

function boundedInteger(value: number | undefined, minimum: number, maximum: number, fallback: number): number {
  return Number.isInteger(value) && Number(value) >= minimum && Number(value) <= maximum
    ? Number(value)
    : fallback;
}

function cleanString(value: unknown): string | undefined {
  const text = typeof value === "string" ? value.trim() : "";
  return text || undefined;
}

function sessionMatches(session: SessionHistoryJsonObject, captureId: string): boolean {
  return session.venueSessionId === captureId || session.captureId === captureId;
}

function unixMillis(value: unknown): number | undefined {
  const parsed = typeof value === "string" || typeof value === "number" ? Date.parse(String(value)) : Number.NaN;
  return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : undefined;
}

function metadataInteger(recording: RecordingAsset, key: string): number | undefined {
  const value = recording.metadata?.[key];
  return typeof value === "number" && Number.isSafeInteger(value) && value > 0 ? value : undefined;
}

function jsonObject(value: unknown): SessionHistoryJsonObject {
  return JSON.parse(JSON.stringify(value)) as SessionHistoryJsonObject;
}
